<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-J3TD01V" failures="0" tests="6" name="testCases.TC003_Loginddt" time="0.710" errors="1" timestamp="2024-09-10T10:57:14 IST" skipped="5">
  <testcase classname="testCases.TC003_Loginddt" name="setup" time="0.705">
    <error message="Cannot invoke &quot;String.equalsIgnoreCase(String)&quot; because the return value of &quot;java.util.Properties.getProperty(String)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "java.util.Properties.getProperty(String)" is null
at TestBase.BaseClass.setup(BaseClass.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <testcase classname="testCases.TC003_Loginddt" name="verify_LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="testCases.TC003_Loginddt" name="verify_LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="testCases.TC003_Loginddt" name="verify_LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="testCases.TC003_Loginddt" name="verify_LoginDDT" time="0.000">
    <skipped/>
  </testcase> <!-- verify_LoginDDT -->
  <testcase classname="testCases.TC003_Loginddt" name="verify_LoginDDT" time="0.005">
    <skipped/>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- testCases.TC003_Loginddt -->
